spring:
  application:
    name: workeffort-service

server:
  port: 2222


eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.31:1111/eureka/
    instance:
      leaseRenewalIntervalInSecondes: 5


business:
  endpoint:
    protocol: http
    host: 192.168.1.31
    port: 8080


ms:
  user:
    endpoint:
      protocol: http
      host: 192.168.1.31
      port: 2223