spring:
  application:
    name: workeffort-service

server:
  port: 2222


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    instance:
      leaseRenewalIntervalInSecondes: 5


business:
  endpoint:
    protocol: http
    host: localhost
    port: 8080


ms:
  user:
    endpoint:
      protocol: http
      host: localhost
      port: 2223