spring:
  application:
    name: workeffort-service
#  freemarker:
#    enabled: false
#  thymeleaf:
#    cache: false
#    prefix: classpath:/workeffort-server/templates/


#error:
#  path: /error

server:
  port: 2222




eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    instance:
      leaseRenewalIntervalInSecondes: 5

