package com.kyle.microservices.service.getWorkEfforts;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-07-08T23:58:09.252+12:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://ofbiz.apache.org/service/", name = "getWorkEffortsPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface GetWorkEffortsPortType {

    @WebMethod(action = "http://localhost:8080/webtools/control/SOAPService")
    @WebResult(name = "map-HashMap", targetNamespace = "http://ofbiz.apache.org/service/", partName = "map-HashMap")
    public MapMap getWorkEfforts(
            @WebParam(partName = "map-Map", name = "map-Map")
                    MapMap mapMap
    );
}
