package com.kyle.microservices.service.getWorkEfforts;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-26T22:07:03.327+12:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "getWorkEfforts", 
                  wsdlLocation = "http://localhost:8080/webtools/control/SOAPService/getWorkEfforts?wsdl",
                  targetNamespace = "http://ofbiz.apache.org/service/") 
public class GetWorkEfforts extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ofbiz.apache.org/service/", "getWorkEfforts");
    public final static QName GetWorkEffortsPort = new QName("http://ofbiz.apache.org/service/", "getWorkEffortsPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/webtools/control/SOAPService/getWorkEfforts?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetWorkEfforts.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/webtools/control/SOAPService/getWorkEfforts?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetWorkEfforts(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetWorkEfforts(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetWorkEfforts() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public GetWorkEfforts(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GetWorkEfforts(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GetWorkEfforts(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns GetWorkEffortsPortType
     */
    @WebEndpoint(name = "getWorkEffortsPort")
    public GetWorkEffortsPortType getGetWorkEffortsPort() {
        return super.getPort(GetWorkEffortsPort, GetWorkEffortsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetWorkEffortsPortType
     */
    @WebEndpoint(name = "getWorkEffortsPort")
    public GetWorkEffortsPortType getGetWorkEffortsPort(WebServiceFeature... features) {
        return super.getPort(GetWorkEffortsPort, GetWorkEffortsPortType.class, features);
    }

}
