
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.kyle.microservices.service.getWorkEfforts;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-26T22:07:03.299+12:00
 * Generated source version: 3.1.11
 * 
 */

@WebService(
                      serviceName = "getWorkEfforts",
                      portName = "getWorkEffortsPort",
                      targetNamespace = "http://ofbiz.apache.org/service/",
                      wsdlLocation = "http://localhost:8080/webtools/control/SOAPService/getWorkEfforts?wsdl",
                      endpointInterface = "com.kyle.microservices.service.getWorkEfforts.GetWorkEffortsPortType")
                      
public class GetWorkEffortsPortImpl implements GetWorkEffortsPortType {

    private static final Logger LOG = Logger.getLogger(GetWorkEffortsPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.kyle.microservices.service.getWorkEfforts.GetWorkEffortsPortType#getWorkEfforts(com.kyle.microservices.service.getWorkEfforts.MapMap mapMap)*
     */
    public void getWorkEfforts(javax.xml.ws.Holder<MapMap> mapMap) { 
        LOG.info("Executing operation getWorkEfforts");
        System.out.println(mapMap.value);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
