
package com.kyle.microservices.service.getWorkEfforts;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-26T22:07:03.200+12:00
 * Generated source version: 3.1.11
 * 
 */
public final class GetWorkEffortsPortType_GetWorkEffortsPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ofbiz.apache.org/service/", "getWorkEfforts");

    private GetWorkEffortsPortType_GetWorkEffortsPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = GetWorkEfforts.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GetWorkEfforts ss = new GetWorkEfforts(wsdlURL, SERVICE_NAME);
        GetWorkEffortsPortType port = ss.getGetWorkEffortsPort();  
        
        {
        System.out.println("Invoking getWorkEfforts...");
        MapMap _getWorkEfforts_mapMapVal = new MapMap();
        javax.xml.ws.Holder<MapMap> _getWorkEfforts_mapMap = new javax.xml.ws.Holder<MapMap>(_getWorkEfforts_mapMapVal);
        port.getWorkEfforts(_getWorkEfforts_mapMap);

        System.out.println("getWorkEfforts._getWorkEfforts_mapMap=" + _getWorkEfforts_mapMap.value);

        }

        System.exit(0);
    }

}
