package com.kyle.microservices.service.getWorkEfforts;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-26T22:07:03.320+12:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://ofbiz.apache.org/service/", name = "getWorkEffortsPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface GetWorkEffortsPortType {

    @WebMethod(action = "http://localhost:8080/webtools/control/SOAPService")
    public void getWorkEfforts(
            @WebParam(partName = "map-Map", mode = WebParam.Mode.INOUT, name = "map-Map")
                    javax.xml.ws.Holder<MapMap> mapMap
    );
}
